services:
  fastapi:
    build:
      context: .
      dockerfile: src/api/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env


  data_processor:
    build:
      context: .
      dockerfile: src/data_processing/Dockerfile.proc
    command: ["/entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env


  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      # interval: 10s
      timeout: 5s
      retries: 2
volumes:
  postgres_data:
